export type ProductSpecs = {
  handle: string;
  title: string;
  cpnpReference?: string;
  content?: string;
  allergens?: string[];
  inci?: string[];
  tagline?: string;
  benefits?: string[];
  usage?: string[];
};

export const PRODUCT_SPECS: Record<string, ProductSpecs> = {
  // Beauty line (examples)
  "crema-skin-total-repair": {
    handle: "crema-skin-total-repair",
    title: "Crema Rigenerante Viso/Corpo",
    cpnpReference: "4237731",
    content: "50 ml | 1.7 fl.OZ",
    allergens: ["Limonene"],
    inci: [
      "Helianthus annus seed oil",
      "Olea europea fruit oil",
      "Acque distillate",
      "Laurus nobilis leaf extract",
      "Cannabis sativa seed oil",
      "Rosmarinus officinalis leaf extract",
      "Timus vulgaris leaf extract",
      "Rosa canina fruit extract",
      "Triticum vulgare germ oil",
      "Caprylic/capric triglycerides",
      "Shea butter",
      "Glycerin",
      "Cetearyl olivate",
      "Glyceryl stearate SE",
      "Cannabidiol",
      "Eucalyptus globulus leaf oil",
      "Eugenia caryophyllus bud oil",
      "Cannabis sativa leaf extract",
      "Ascorbic acid",
      "Xanthan gum",
      "Tocopheryl acetate",
    ],
    tagline: "Full‑spectrum CBD comfort with nourishing botanicals",
    benefits: [
      "Supports everyday skin balance",
      "Helps the skin feel calmer",
      "Hydrating and nourishing texture",
      "Antioxidant support from botanical oils",
    ],
    usage: [
      "Apply a small amount to clean, dry skin",
      "Massage until absorbed, morning and evening",
      "Suitable for face and body",
    ],
  },
  "candela-body-pleasure": {
    handle: "candela-body-pleasure",
    title: "Candela Body Pleasure",
    cpnpReference: "4237673",
    content: "100 ml | 3.4 fl.OZ",
    allergens: ["limonene", "cinnamal", "coumarin"],
    inci: [
      "hidrogenated soybean oil",
      "helianthus annus seed oil",
      "cocos nucifera oil",
      "olea europea fruit oil",
      "theobroma cacao seed butter",
      "calendula officinalis leaf extract",
      "ricinus communis oil",
      "cannabis sativa seed oil",
      "salvia sclarea leaf extract",
      "rosa canina friut extract",
      "taraxacum officinale root extract",
      "cera alba",
      "caprylic/capric triglycerides",
      "cannabidiol",
      "cinnamon bark essential oil",
      "citrus aurantium dolcis peel oil",
      "cannabis sativa leaf extract",
      "ascorbic acid",
      "tocopheryl acetate",
    ],
    tagline: "Warm, sensorial massage candle with botanical oils",
    benefits: [
      "Transforms into a warm, silky oil",
      "Sensorial ritual with botanical notes",
      "Designed for mindful massage",
    ],
    usage: [
      "Light the candle and allow a pool of oil to form",
      "Extinguish and pour a small amount onto skin",
      "Massage gently",
    ],
  },
  "crema-sanadol-plus": {
    handle: "crema-sanadol-plus",
    title: "Crema Sanadol Plus",
    cpnpReference: "4238058",
    content: "50 ml | 1.7 fl.OZ",
    allergens: ["Limonene"],
    inci: [
      "Acque distillate",
      "Helianthus annus seed oil",
      "Olea europea fruit oil",
      "Laurus nobilis leaf extract",
      "Timus vulgaris leaf extract",
      "Rosmarinus officinalis leaf extract",
      "Cannabis sativa seed oil",
      "Rosa canina fruit extract",
      "Shea butter",
      "Caprylic/capric triglycerides",
      "Triticum vulgare germ oil",
      "Glycerin",
      "Cetearyl olivate",
      "Glyceryl stearate SE",
      "Cannabidiol",
      "Eucalyptus globulus leaf oil",
      "Eugenia caryophyllus bud oil",
      "Cannabis sativa leaf extract",
      "Ascorbic acid",
      "Xanthan gum",
      "Tocopheryl acetate",
    ],
    tagline: "Comfort quotidiano con CBD full‑spectrum",
    benefits: [
      "Supporta l’equilibrio della pelle",
      "Aiuta la pelle a sentirsi più calma",
      "Texture confortevole per uso quotidiano",
    ],
    usage: [
      "Applicare su pelle pulita e asciutta",
      "Massaggiare fino ad assorbimento",
      "Usare mattina e sera",
    ],
  },
  "forever-young-cream": {
    handle: "forever-young-cream",
    title: "Forever Young Cream",
    cpnpReference: "4237711",
    content: "25 ml | 0.85 fl.OZ",
    allergens: ["citral", "citronellal", "citronellol", "geraniol"],
    inci: [
      "helianthus annus seed oil",
      "olea europea fruit oil",
      "calendula officinalis leaf extract",
      "malva sylvestris flower leaf extract",
      "ricinus communis oil",
      "aloe barbadensis leaf juice",
      "chamomilla recutica leaf extract",
      "prunus amygdalus dulcis fruit extract",
      "acque distillate",
      "shea butter",
      "cannabidiol",
      "caprylic/capric triglycerides",
      "cera alba",
      "cetaeryl olivate",
      "glyceryl stearate se",
      "cannabis sativa seed oil",
      "sodium hyaluronic acid",
      "ascorbic acid",
      "tocopheryl acetate",
    ],
    tagline: "Idratazione e comfort per un aspetto più fresco",
    benefits: [
      "Supporta la naturale morbidezza della pelle",
      "Aiuta a migliorare la sensazione di elasticità",
      "Texture nutriente e vellutata",
    ],
    usage: [
      "Applicare una piccola quantità sul viso",
      "Massaggiare delicatamente fino ad assorbimento",
      "Usare quotidianamente",
    ],
  },
  "forever-young-stick": {
    handle: "forever-young-stick",
    title: "Forever Young Stick",
    cpnpReference: "4237711",
    content: "5 ml | 0.2 fl.OZ",
    allergens: ["citral", "citronellal", "citronellol", "geraniol"],
    inci: [
      "helianthus annus seed oil",
      "olea europea fruit oil",
      "cera alba",
      "melissa officinalis leaf oil",
      "malva sylvestris flower leaf extract",
      "ricinus communis oil",
      "aloe barbadensis leaf juice",
      "chamomilla recutica leaf extract",
      "prunus amygdalus dulcis fruit extract",
      "acque distillate",
      "shea butter",
      "cannabidiol",
      "caprylic/capric triglycerides",
      "cetaeryl olivate",
      "glyceryl stearate se",
      "cannabis sativa seed oil",
      "sodium hyaluronic acid",
      "ascorbic acid",
      "tocopheryl acetate",
    ],
    tagline: "Stick mirato per comfort quotidiano della pelle",
    benefits: [
      "Dona una sensazione lenitiva sulle aree mirate",
      "Pratico per ritocchi durante la giornata",
      "Finitura naturale non appiccicosa",
    ],
    usage: [
      "Applicare sulle aree interessate secondo necessità",
      "Riapplicare durante il giorno",
    ],
  },
  "lips-defence": {
    handle: "lips-defence",
    title: "Lips Defence",
    cpnpReference: "4237721",
    content: "5 ml | 0,2 fl.OZ",
    allergens: ["limonene", "linalool"],
    inci: [
      "helianthus annus seed oil",
      "olea europea fruit oil",
      "melissa officinalis leaf oil",
      "cera alba",
      "prunus amygdalus dulcis fruit extract",
      "lavandula angustifolia leaf extract",
      "hypericum perforatum leaf extract",
      "theobroma cacao seed butter",
      "argania spinosa kernel oil",
      "cannabis sativa seed oil",
      "shea butter",
      "caprylic/capric triglycerides",
      "mentha piperita oil",
      "citrus bergamia peel oil",
      "cannabidiol",
      "cannabis sativa leaf extract",
      "ascorbic acid",
      "tocopherol",
    ],
    tagline: "Balsamo labbra protettivo con oli botanici",
    benefits: [
      "Aiuta le labbra a sentirsi morbide e protette",
      "Comfort quotidiano con finitura naturale",
      "Senza effetto appiccicoso",
    ],
    usage: [
      "Applicare sulle labbra pulite secondo necessità",
      "Riapplicare durante la giornata",
    ],
  },
  "olio-body-relief": {
    handle: "olio-body-relief",
    title: "Olio Body Relief",
    content: "100 ml | 3.4 fl.OZ",
    cpnpReference: "4237684",
    allergens: ["Nessun allergene dichiarato"],
    tagline: "Olio corpo pre‑gara e post‑gara con CBD",
    benefits: [
      "Supporta attivazione muscolare pre‑gara",
      "Aiuta il defaticamento e la sensazione di sollievo post‑gara",
      "Favorisce drenaggio e comfort cutaneo",
    ],
    usage: [
      "Applicare una piccola quantità a livello topico sulle aree interessate",
      "In alternativa applicare sulla pianta del piede",
      "Usare prima dell’attività per attivazione, dopo per defaticamento",
    ],
    inci: [
      "Helianthus annus seed oil",
      "Calendula officinalis extract",
      "Hedera helix (ivy) extract",
      "Argania spinosa kernel oil",
      "Humulus lupulus (hop) extract",
      "Cannabidiol",
    ],
  },
  // Additional catalogue entries (to be completed with official specs)
  "contorno-occhi-stick": {
    handle: "contorno-occhi-stick",
    title: "Contorno Occhi Stick",
    tagline: "Cooling CBD eye care for everyday comfort",
    benefits: [
      "Helps the eye area feel soothed",
      "Lightweight comfort with botanical oils",
      "Supports daily hydration",
    ],
    usage: [
      "Apply gently around the eye area",
      "Use morning and evening",
      "Avoid direct contact with eyes",
    ],
  },
  "contorno-occhi-cream": {
    handle: "contorno-occhi-cream",
    title: "Contorno Occhi Cream",
    tagline: "Nourishing CBD cream for the delicate eye area",
    benefits: [
      "Supports the skin’s natural comfort",
      "Helps the delicate area feel calmer",
      "Smooth, nourishing texture",
    ],
    usage: [
      "Apply a small amount to the eye contour",
      "Massage lightly until absorbed",
      "Use daily, morning and evening",
    ],
  },
  "burrocacao-protettivo": {
    handle: "burrocacao-protettivo",
    title: "Burrocacao Protettivo",
    tagline: "Protective CBD lip balm with natural oils",
    benefits: [
      "Helps lips feel protected and soft",
      "Botanical oils for everyday comfort",
      "Non‑sticky, natural finish",
    ],
    usage: [
      "Apply to clean lips as needed",
      "Reapply throughout the day",
    ],
  },
  "crema-lenitiva-corpo": {
    handle: "crema-lenitiva-corpo",
    title: "Crema Lenitiva Corpo",
    tagline: "Soothing body care with full‑spectrum CBD",
    benefits: [
      "Supports skin comfort and balance",
      "Helps the skin feel calmer",
      "Silky texture for daily use",
    ],
    usage: [
      "Apply generously to clean, dry skin",
      "Massage until absorbed",
      "Use daily or as needed",
    ],
  },
  "candela-massaggio": {
    handle: "candela-massaggio",
    title: "Candela da Massaggio",
    tagline: "Warm, sensorial massage candle with botanical oils",
    benefits: [
      "Transforms into a warm, silky oil",
      "Sensorial ritual with botanical notes",
      "Designed for mindful massage",
    ],
    usage: [
      "Light the candle and allow a pool of oil to form",
      "Extinguish and pour a small amount onto skin",
      "Massage gently",
    ],
  },
  "olio-massaggio-full-body": {
    handle: "olio-massaggio-full-body",
    title: "Olio da Massaggio Full Body",
    tagline: "Silky massage oil with full‑spectrum extracts",
    benefits: [
      "Glides easily for comfortable massage",
      "Botanical blend with a natural finish",
      "Supports a relaxing ritual",
    ],
    usage: [
      "Warm a small amount in hands",
      "Apply and massage onto the body",
      "Use as needed",
    ],
  },
  // Functional oils and supplements
  "ecs-activator": {
    handle: "ecs-activator",
    title: "ECS Activator",
    tagline: "Daily support for endocannabinoid balance",
  },
  "sanadol-plus": {
    handle: "sanadol-plus",
    title: "Sanadol+",
    tagline: "Full‑spectrum CBD oil with native terpenes",
  },
  "relax": {
    handle: "relax",
    title: "Relax",
    tagline: "Everyday calm with full‑spectrum CBD",
  },
  "positivity": {
    handle: "positivity",
    title: "Positivity",
    tagline: "Uplifting terpene‑rich botanical profile",
  },
};

export function getSpecsForProduct(handle?: string, title?: string): ProductSpecs | undefined {
  if (handle && PRODUCT_SPECS[handle]) return PRODUCT_SPECS[handle];
  if (!title) return undefined;
  const norm = title.trim().toLowerCase();
  return Object.values(PRODUCT_SPECS).find((s) => s.title.trim().toLowerCase() === norm);
}
